import Foundation
import WinmacCore

@MainActor
public final class DiagnosticsViewModel: ObservableObject {
    private let service: DiagnosticsProviding

    @Published public private(set) var report: DiagnosticReport?
    @Published public private(set) var loadState: LoadState = .idle
    @Published public private(set) var lastExportPath: String?

    public init(service: DiagnosticsProviding = DiagnosticsService()) {
        self.service = service
    }

    public var reportJSON: String {
        guard let report else { return "" }
        return JSONFormatting.prettyPrinted(report)
    }

    public func generate() async {
        loadState = .loading
        report = await service.makeReport(notes: ["Generated by Winmac."])
        loadState = .idle
    }

    public func export(to url: URL) async {
        let reportToExport: DiagnosticReport
        if let report {
            reportToExport = report
        } else {
            reportToExport = await service.makeReport(notes: ["Generated by Winmac export."])
            report = reportToExport
        }

        loadState = .loading

        do {
            try await service.export(report: reportToExport, to: url)
            lastExportPath = url.standardizedFileURL.path
            loadState = .idle
        } catch {
            loadState = .failed(error.localizedDescription)
        }
    }
}