import Foundation
import WinmacCore

@main
struct WinmacCLI {
    static func main() {
        do {
            try run(arguments: Array(CommandLine.arguments.dropFirst()))
        } catch {
            fputs("error: \(error.localizedDescription)\n", stderr)
            Foundation.exit(1)
        }
    }

    static func run(arguments: [String]) throws {
        guard let command = arguments.first else {
            printHelp()
            return
        }

        let remainingArguments = Array(arguments.dropFirst())

        switch command {
        case "help", "--help", "-h":
            printHelp()
        case "scan":
            try scan(arguments: remainingArguments)
        case "bottle":
            try bottle(arguments: remainingArguments)
        case "launch-plan":
            try launchPlan(arguments: remainingArguments)
        case "diagnostics":
            try diagnostics(arguments: remainingArguments)
        case "runtimes":
            try runtimes(arguments: remainingArguments)
        case "version", "--version":
            print("winmac-cli 0.1.0-dev")
        default:
            throw CLIError.unknownCommand(command)
        }
    }

    private static func scan(arguments: [String]) throws {
        let options = ArgumentReader(arguments: arguments)
        let steamRootPath = try options.optionalValue(after: "--steam-root")
        let steamRootURL = steamRootPath.map(expandedURL(from:))
        let games = try SteamLibraryScanner().scan(steamRoot: steamRootURL)
        try printJSON(games)
    }

    private static func bottle(arguments: [String]) throws {
        guard arguments.first == "validate" else {
            throw CLIError.usage("Usage: winmac-cli bottle validate <prefix-path>")
        }

        guard arguments.count >= 2 else {
            throw CLIError.usage("Usage: winmac-cli bottle validate <prefix-path>")
        }

        let validation = BottleManager().validate(prefixURL: expandedURL(from: arguments[1]))
        try printJSON(validation)
    }

    private static func launchPlan(arguments: [String]) throws {
        let options = ArgumentReader(arguments: arguments)
        guard let executablePath = try options.optionalValue(after: "--exe") else {
            throw CLIError.usage("Usage: winmac-cli launch-plan --exe <path> --prefix <path> [--no-validate]")
        }
        guard let prefixPath = try options.optionalValue(after: "--prefix") else {
            throw CLIError.usage("Usage: winmac-cli launch-plan --exe <path> --prefix <path> [--no-validate]")
        }

        let validateInputs = !arguments.contains("--no-validate")
        let plan = try LaunchPlanner().makePlan(
            executableURL: expandedURL(from: executablePath),
            prefixURL: expandedURL(from: prefixPath),
            validateInputs: validateInputs
        )
        try printJSON(plan)
    }

    private static func diagnostics(arguments: [String]) throws {
        guard arguments.first == "export" else {
            throw CLIError.usage("Usage: winmac-cli diagnostics export --output <path>")
        }

        let options = ArgumentReader(arguments: Array(arguments.dropFirst()))
        guard let outputPath = try options.optionalValue(after: "--output") else {
            throw CLIError.usage("Usage: winmac-cli diagnostics export --output <path>")
        }

        let exporter = DiagnosticsExporter()
        let report = exporter.makeReport(notes: ["Generated by winmac-cli diagnostics export."])
        try exporter.export(report: report, to: expandedURL(from: outputPath))
        print("Wrote diagnostics to \(outputPath)")
    }

    private static func runtimes(arguments: [String]) throws {
        guard arguments.first == "list" else {
            throw CLIError.usage("Usage: winmac-cli runtimes list")
        }

        let message = [
            "status": "runtime download support is not implemented yet",
            "policy": "open-source runtimes only"
        ]
        try printJSON(message)
    }

    private static func expandedURL(from path: String) -> URL {
        URL(fileURLWithPath: NSString(string: path).expandingTildeInPath).standardizedFileURL
    }

    private static func printHelp() {
        print(
            """
            winmac-cli

            Commands:
              scan [--steam-root <path>]                         Scan local Steam manifests and print games as JSON.
              bottle validate <prefix-path>                      Validate a Wine prefix/bottle.
              launch-plan --exe <path> --prefix <path>           Build a launch plan without executing Wine.
              launch-plan --exe <path> --prefix <path> --no-validate
              diagnostics export --output <path>                 Write a sanitized diagnostics JSON file.
              runtimes list                                      Show runtime manager status.
              version                                            Print CLI version.
              help                                               Show this help.
            """
        )
    }

    private static func printJSON<T: Encodable>(_ value: T) throws {
        let encoder = JSONEncoder()
        encoder.outputFormatting = [.prettyPrinted, .sortedKeys]
        encoder.dateEncodingStrategy = .iso8601
        let data = try encoder.encode(value)
        print(String(decoding: data, as: UTF8.self))
    }
}

private enum CLIError: Error, LocalizedError, Equatable {
    case unknownCommand(String)
    case usage(String)
    case missingValue(String)

    var errorDescription: String? {
        switch self {
        case let .unknownCommand(command):
            return "Unknown command: \(command). Run `winmac-cli help`."
        case let .usage(message):
            return message
        case let .missingValue(option):
            return "Missing value for \(option)."
        }
    }
}

private struct ArgumentReader {
    let arguments: [String]

    func optionalValue(after option: String) throws -> String? {
        guard let optionIndex = arguments.firstIndex(of: option) else {
            return nil
        }

        let valueIndex = arguments.index(after: optionIndex)
        guard valueIndex < arguments.endIndex else {
            throw CLIError.missingValue(option)
        }

        return arguments[valueIndex]
    }
}